"""empty message

Revision ID: 576b97f4884e
Revises: 
Create Date: 2023-10-15 13:56:20.865729

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "576b97f4884e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id", sa.Integer(), nullable=False, comment="Идентификатор пользователя"
        ),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Имя"),
        sa.Column("surname", sa.String(length=255), nullable=False, comment="Фамилия"),
        sa.Column("email", sa.String(length=255), nullable=False, comment="Email"),
        sa.Column(
            "birthday",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата и время рождения",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
